-- AlterTable
ALTER TABLE `Movie` MODIFY `duration` INTEGER NOT NULL DEFAULT 0,
    MODIFY `rating` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `releaseDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
